openapi: 3.0.2
info:
  version: 0.10.0
  title: Nomad
  description: Nomad OpenApi specification
  license:
    name: MIT
paths:
  # agent
  /agent/force-leave:
    $ref: './paths/agent/force-leave.yaml'
  /agent/health:
    $ref: './paths/agent/health.yaml'
  /agent/join:
    $ref: './paths/agent/join.yaml'
  /agent/members:
    $ref: './paths/agent/members.yaml'
  /agent/self:
    $ref: './paths/agent/self.yaml'
  /agent/servers:
    $ref: './paths/agent/servers.yaml'
  /agent/monitor:
    $ref: './paths/agent/monitor.yaml'
  # todo: Agent Runtime Profiles agent/pprof/*

  # job
  /job/{job_id}:
    $ref: './paths/job/$job_id.yaml'
  /job/{job_id}/allocations:
    $ref: './paths/job/$job_id.allocations.yaml'
  /job/{job_id}/deployment:
    $ref: './paths/job/$job_id.deployment.yaml'
  /job/{job_id}/deployments:
    $ref: './paths/job/$job_id.deployments.yaml'
  /job/{job_id}/dispatch:
    $ref: './paths/job/$job_id.dispatch.yaml'
  /job/{job_id}/evaluate:
    $ref: './paths/job/$job_id.evaluate.yaml'
  /job/{job_id}/evaluations:
    $ref: './paths/job/$job_id.evaluations.yaml'
  /job/{job_id}/periodic/force:
    $ref: './paths/job/$job_id.periodic.force.yaml'
  /job/{job_id}/plan:
    $ref: './paths/job/$job_id.plan.yaml'
  /job/{job_id}/revert:
    $ref: './paths/job/$job_id.revert.yaml'
  /job/{job_id}/scale:
    $ref: './paths/job/$job_id.scale.yaml'
  /job/{job_id}/stable:
    $ref: './paths/job/$job_id.stable.yaml'
  /job/{job_id}/summary:
    $ref: './paths/job/$job_id.summary.yaml'
  /job/{job_id}/versions:
    $ref: './paths/job/$job_id.versions.yaml'
  # jobs
  /jobs:
    $ref: './paths/jobs/_.yaml'
  /jobs/parse:
    $ref: './paths/jobs/parse.yaml'
components:
  parameters:
    $ref: './parameters/_index.yaml'
  schemas:
    $ref: './schemas/_index.yaml'
  responses:
    $ref: './responses/_index.yaml'
