get:
  summary: reads information about a specific deployment by ID
  operationId: getDeployment
  tags:
    - deployments
  parameters:
    - $ref: '../../parameters/path/deployment_id.yaml'
  responses:
    '200':
      description: deployment
      content:
        application/json:
          schema:
            $ref: '../../schemas/Deployment.yaml'