post:
  summary: set the health of an allocation that is in the deployment manually
  description: In some use cases, automatic detection of allocation health may not be desired. As such those task groups can be marked with an upgrade policy that uses health_check = "manual". Those allocations must have their health marked manually using this endpoint. Marking an allocation as healthy will allow the rolling upgrade to proceed. Marking it as failed will cause the deployment to fail. This endpoint only triggers a rollback if the most recent stable version of the job has a different specification than the job being reverted
  operationId: setAllocationHealthInDeployment
  tags:
    - deployments
  parameters:
    - $ref: '../../parameters/path/deployment_id.yaml'
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/DeploymentAllocHealthRequest.yaml'
    
  responses:
    '200':
      description: deployment update response
      content:
        application/json:
          schema:
            $ref: '../../schemas/DeploymentUpdateResponse.yaml'