get:
  summary: lists the allocations created or modified for the given deployment
  operationId: getAllocationsForDeployment
  tags:
    - deployments
  parameters:
    - $ref: '../../parameters/path/deployment_id.yaml'
  responses:
    '200':
      description: allocation list response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/AllocationListStub.yaml'