type: object
nullable: true
properties:
  Healthy:
    type: boolean
  Timestamp:
    type: string
    format: date-time
    nullable: true
  Canary:
    type: boolean
  ModifyIndex:
    $ref: './BigInteger.yaml'
