type: object
nullable: true
properties:
  ID:
    type: string
  Name:
    type: string
  Tags:
    type: array
    nullable: true
    items:
      type: string
  CanaryTags:
    type: array
    nullable: true
    items:
      type: string
  EnableTagOverride:
    type: boolean
  PortLabel:
    type: string
  AddressMode:
    type: string
  Checks:
    type: array
    nullable: true
    items:
      $ref: './ServiceCheck.yaml'
  CheckRestart:
    $ref: './CheckRestart.yaml'
  Connect:
    $ref: './ConsulConnect.yaml'
  Meta:
    type: object
    nullable: true
    additionalProperties:
      type: string
  CanaryMeta:
    type: object
    nullable: true
    additionalProperties:
      type: string
